remote_theme: coogie/oscailte

title: Tech Fortress
subtitle: A gaming community established in 2013
description: "Gaming community established in 2013. Hosts Minecraft and Team Fortress 2 servers. IP: tf.robomwm.com"

oscailte:
  social:
    github: TechFortress
  strings:
    hero_title: "Tech Fortress <br /> Gaming community established in 2013"
